"""Generate a PDF document from plain text content using reportlab."""

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer


DOC_TITLES = {
    "commercial_invoice": "COMMERCIAL INVOICE",
    "bill_of_lading": "BILL OF LADING",
    "certificate_of_origin": "CERTIFICATE OF ORIGIN",
    "packing_list": "PACKING LIST",
}


def generate_pdf(text_content: str, output_path: str, doc_type: str = "") -> str:
    """Convert plain text document content into a formatted PDF.

    Args:
        text_content: The document text (as generated by document_generator).
        output_path: Path to write the PDF file.
        doc_type: Document type key for title styling.

    Returns:
        The output_path.
    """
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontSize=14,
        alignment=TA_CENTER,
        spaceAfter=12,
        fontName="Helvetica-Bold",
    )

    heading_style = ParagraphStyle(
        "SectionHead",
        parent=styles["Normal"],
        fontSize=10,
        fontName="Helvetica-Bold",
        spaceAfter=2,
        spaceBefore=8,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=9,
        fontName="Helvetica",
        leading=12,
        spaceAfter=1,
    )

    elements = []
    lines = text_content.strip().split("\n")

    # Section labels that get heading style
    section_labels = {
        "SELLER:", "BUYER:", "SHIPPER:", "CONSIGNEE:", "EXPORTER:",
        "CONSIGNEE / IMPORTER:", "NOTIFY PARTY:", "DESCRIPTION OF GOODS:",
        "SHIPPING MARKS:", "CARGO DETAILS:", "TRANSPORT DETAILS:",
    }

    for line in lines:
        stripped = line.strip()
        if not stripped:
            elements.append(Spacer(1, 4))
            continue

        # Title line (first meaningful line or known doc title)
        if stripped in DOC_TITLES.values():
            elements.append(Paragraph(stripped, title_style))
            elements.append(Spacer(1, 6))
        elif stripped.endswith(":") and stripped in section_labels:
            elements.append(Paragraph(stripped, heading_style))
        elif stripped.startswith("---"):
            elements.append(Spacer(1, 4))
        else:
            # Escape XML special chars for reportlab
            safe = (
                stripped
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
            )
            elements.append(Paragraph(safe, body_style))

    doc.build(elements)
    return output_path
