from models.enums import DocumentType

# Maps LC advice field names -> corresponding field names in each document type
FIELD_MAPPINGS: dict[DocumentType, dict[str, str]] = {
    DocumentType.COMMERCIAL_INVOICE: {
        "beneficiary_name": "seller_name",
        "beneficiary_address": "seller_address",
        "applicant_name": "buyer_name",
        "applicant_address": "buyer_address",
        "lc_number": "lc_reference",
        "currency": "currency",
        "amount": "total_amount",
        "goods_description": "goods_description",
        "hs_codes": "hs_codes",
        "quantity": "quantity",
        "unit_price": "unit_price",
        "incoterms": "incoterms",
        "port_of_loading": "port_of_loading",
        "port_of_discharge": "port_of_discharge",
    },
    DocumentType.BILL_OF_LADING: {
        "beneficiary_name": "shipper_name",
        "beneficiary_address": "shipper_address",
        "applicant_name": "consignee_name",
        "lc_number": "lc_reference",
        "goods_description": "goods_description",
        "quantity": "quantity",
        "port_of_loading": "port_of_loading",
        "port_of_discharge": "port_of_discharge",
        "latest_shipment_date": "shipped_on_board_date",
        "partial_shipments": "partial_shipments",
        "transhipment": "transhipment",
    },
    DocumentType.CERTIFICATE_OF_ORIGIN: {
        "beneficiary_name": "exporter_name",
        "beneficiary_address": "exporter_address",
        "applicant_name": "importer_name",
        "applicant_address": "importer_address",
        "goods_description": "goods_description",
        "hs_codes": "hs_codes",
        "quantity": "quantity",
    },
    DocumentType.PACKING_LIST: {
        "beneficiary_name": "shipper_name",
        "beneficiary_address": "shipper_address",
        "applicant_name": "consignee_name",
        "applicant_address": "consignee_address",
        "goods_description": "goods_description",
        "quantity": "quantity",
        "lc_number": "lc_reference",
    },
}

# Categorize fields for display
FIELD_CATEGORIES: dict[str, str] = {
    "beneficiary_name": "core",
    "beneficiary_address": "core",
    "applicant_name": "core",
    "applicant_address": "core",
    "lc_number": "core",
    "currency": "core",
    "amount": "core",
    "expiry_date": "core",
    "goods_description": "goods",
    "hs_codes": "goods",
    "quantity": "goods",
    "unit_price": "goods",
    "incoterms": "goods",
    "port_of_loading": "shipping",
    "port_of_discharge": "shipping",
    "latest_shipment_date": "shipping",
    "partial_shipments": "shipping",
    "transhipment": "shipping",
}
